### ISSUE TITLE
Non-ASCII characters in Julia

### ISSUE THREAD

**Issue by Haksell** [codewars/codemirror-unicode-helper#1]
**Is your feature request related to a problem? Please describe.**
The Julia programming language uses a lot of non-ASCII characters to represent common mathematical functions. It would be nice to be able to generate them directly from the website, instead of having to keep a Julia REPL on the side.
Considering the size of the Julia userbase on codewars, I realise that it is probably not a very crucial feature request.

**Describe the solution you'd like**
I would like the same functionality as in a Julia REPL or notebook. When I type `\sqrt` followed by `<TAB>`, it should replace what I typed with `√`.

**Comment by Haksell** [comment]
Also, I must say I don't really understand the tool that you linked. Is it just a standalone editor with no real relation to codewars? (apart from the URL)

I think if it comes to that, I prefer continuing like I do now. It's not too much of a hassle anyway, I'd just like to be able to type `τ = 2π` quickly to feel leet.

**Comment by kazk** [comment]
It's an extension for [CodeMirror editor](https://codemirror.net/) that Codewars uses. The link I gave you is just a standalone demo for the extension.
If you try Agda on Codewars, you should see the same thing working there too.

**Comment by Haksell** [comment]
Oh, nice. Thanks for the clarification.

**Comment by kazk** [comment]
![unicode-helper](https://user-images.githubusercontent.com/639336/100401638-ee435e80-300e-11eb-8069-f9f2bd51efd2.gif)

See https://codewars.github.io/codemirror-unicode-helper/

To add more sequences, just update https://github.com/codewars/codemirror-unicode-helper/blob/main/src/default.ts and open a pull request.

Once it's been tested, I can enable this on Codewars for Julia.

**Comment by Haksell** [comment]
Can't make it work, the suggestions don't come up and when I press `<TAB>`, it just inserts a tab character.
I'm on MacOS Catalina 10.15.6. Tried on Chrome and Firefox.

**Comment by kazk** [comment]
Did you enter the backslash first? ~~`\` should show the suggestions automatically.~~ (changed to require at least one character after the back slash) Then keep entering the sequence to narrow it down. Pressing `<TAB>` when the suggestion is open will replace the sequence with the symbol.
I've tested on Firefox and Chrome. I can try with macOS later.

If it still doesn't work, can you check if there's anything shown in the console?

**Comment by Haksell** [comment]
Apart from some CSS warnings (maybe caused by an extension, since nothing is shown on Firefox), there is nothing in the console.

<img width="1679" alt="Screenshot 2020-11-27 at 03 50 49" src="https://user-images.githubusercontent.com/33573717/100405444-ea8df700-3063-11eb-9274-2ddf6b3269ed.png">

And yes, this is what I did. No suggestion appears after `\`. And even if I have entered `\pi`, pressing `<TAB>` will just insert a tab character.

**Comment by kazk** [comment]
Is the "Use Unicode Helper" checked? Can you try again after toggling the checkbox off and on?
I tried on macOS with Firefox and it works the same as my Linux laptop.

**Comment by Haksell** [comment]
It is checked and still doesn't work after turning it off and on.
I also tried in Incognito on Chrome and Firefox for good measure but still nothing.
Also tried the four different key mappings.

Here is a screen capture, maybe I'm missing something obvious:
Edit: for some reason the GIF conversion has slowed it down a lot, sorry for long boring video.
![Screen Recording 2020-11-27 at 04 29 59](https://user-images.githubusercontent.com/33573717/100407839-c59c8280-3069-11eb-8d21-8f75f4d73cae.gif)

**Comment by XRFXLP** [comment]
Yes, it works for me.
I'm tried this on Mint 20, browser: Brave 1.21 and Firefox 86.

**Comment by kazk** [comment]
Thanks @XRFXLP. I might just deploy it because it seems to work for some, and it shouldn't break anything even if it doesn't work.

**Comment by kazk** [comment]
Deployed
